name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: adopt
          java-version: 17
      - name: Build LimboAuth (skip checkstyle)
        run: ./gradlew build -x checkstyleMain -x checkstyleTest
      - name: Upload LimboAuth
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LimboAuth
          path: "build/libs/limboauth*.jar"
      - name: Find git version
        id: git-version
        run: echo "id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Find correct JAR
        if: ${{ github.event_name == 'push' }}
        id: find-jar
        run: |
          output="$(find build/libs/ ! -name "*-javadoc.jar" ! -name "*-sources.jar" -type f -printf "%f\n")"
          echo "::set-output name=jarname::$output"
      - name: Release the build
        if: ${{ github.event_name == 'push' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/libs/${{ steps.find-jar.outputs.jarname }}
          body: "Fixed for Velocity 4.2.1 compat - custom rate limiter replaces internal Ratelimiter"
          prerelease: true
          name: Dev-build ${{ steps.git-version.outputs.id }}
          tag: dev-build
